name: Release

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - { version: ubuntu-latest, name: linux }
          - { version: windows-latest, name: windows }
          - { version: macos-latest, name: macos }

    runs-on: ${{matrix.os.version}}
    steps:
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: react-props-replacer.${{matrix.os.name}}.zip
          directory: ./target/release
          path: react-props-replacer*
          exclusions: react-props-replacer.*d*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v0.5.0
          files: ./target/release/react-props-replacer.${{matrix.os.name}}.zip
