name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - { version: ubuntu-latest, name: unknown-linux }
          - { version: windows-latest, name: pc-windows }
          - { version: macos-latest, name: apple-darwin }

    runs-on: ${{matrix.os.version}}
    permissions:
      contents: write
    steps:
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: react-props-replacer.${{matrix.os.name}}.zip
          directory: ./target/release
          path: react-props-replacer*
          exclusions: react-props-replacer.*d*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ./target/release/react-props-replacer.${{matrix.os.name}}.zip
