name: Release

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - { version: ubuntu-latest, name: linux }
          - { version: windows-latest, name: windows }
          - { version: macos-latest, name: macos }

    runs-on: ${{matrix.os.version}}
    env:
      FILENAME: react-props-replacer.${{matrix.os.name}}
    steps:
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --all --release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: ${{FILENAME}}.zip
          directory: ./target/release
          path: react-props-replacer*
          exclusions: react-props-replacer.*d*

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: $FILENAME
          path: ./target/release/${{FILENAME}}.zip
