name: Release

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --all --release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: react-props-replacer.${{matrix.os}}.zip
          path: ./target/release/react-props-replacer*
          exclusions: ./target/release/react-props-replacer.*d*

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-props-replacer.${{matrix.os}}
          path: react-props-replacer.${{matrix.os}}.zip
